export const actionTypes = {
  GET_CITIES: "GET_CITIES",
  GET_MAIN_DATA: "GET_MAIN_DATA",
  GET_SHOP_DRAWER_DATA: "GET_SHOP_DRAWER_DATA",
  SHOP_SEARCH_VALUE: "SHOP_SEARCH_VALUE",
  FIND_NEW_CITIES: "FIND_NEW_CITIES",
  SELECT_SHOP: "SELECT_SHOP",
  GET_ALL_PRODUCTS: "GET_ALL_PRODUCTS",
  GET_SHOP: "GET_SHOP",
};
